# Generated by Django 3.1.4 on 2020-12-10 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=50)),
                ('descriere', models.TextField()),
                ('completat', models.BooleanField(default=False)),
                ('data_creare', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
