# Generated by Django 3.1.4 on 2020-12-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='prioritate',
            field=models.BooleanField(default=False),
        ),
    ]
